language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 12.19.0
before_install:
  - npm i -g npm@^6.14.8
before_script:
  - npm prune
script:
  - npm run test
install: npm install
